--CRIANDO PARA PostegreSQL

CREATE TABLE MEDICO (
   MEDCODIGO INTEGER PRIMARY KEY,
   MEDNOME VARCHAR(100)
);

CREATE TABLE Consulta (
   CHAVE ESTRANGEIRA MEDCODIGO INTEGER,
   CHAVE ESTRANGEIRA PACCODIGO INTEGER,
   CHAVE PRIMARIA CONCODIGO INTEGER,
   DATA DATE,
   FOREIGN KEY (MEDCODIGO) REFERENCES Medico(MEDCODIGO),
   FOREIGN KEY (PACCODIGO) REFERENCES Paciente(PACCODIGO),
   PRIMARY KEY (CONCODIGO)
);

CREATE TABLE PACIENTE (
   PACCODIGO INTEGER PRIMARY KEY,
   PACCNOME VARCHAR(100)
);

CREATE TABLE PRESCRICAO (
   CONCODIGO INTEGER,
   MDCODIGO INTEGER,
   POSOLOGIA VARCHAR(200),
   PRIMARY KEY (CONCODIGO, MDCODIGO)
);


CREATE TABLE MEDICAMENTO (
   MDCODIGO INT PRIMARY KEY,
   MDNOME VARCHAR(100) NOT NULL
);


--Incluir uma nova coluna DATANASCIMENTO na tabela MÉDICO, com comando ALTER TABLE é possível adicionar uma coluna (0,5).

ALTER TABLE MEDICO
ADD DATANASCIMENTO DATE;

OU

ALTER TABLE MEDICO
ADD COLUMN DATANASCIMENTO DATE;

--colocando Data

UPDATE MEDICO
SET DATANASCIMENTO = '1990-10-30'
WHERE NOME = 'DR PEREIRA';

UPDATE MEDICO
SET DATANASCIMENTO = '1983-10-10'
WHERE NOME = 'EDSON KLOCK';



--Inserir data de nascimento 

INSERT INTO MEDICO (DATANASCIMENTO)
VALUES ('1987-10-30');

--4.	Inserir 2 tuplas em cada tabela (0,5). Usar o INSERT

--INSERT INTO <NOMETABELA> (COLUNA1, COLUNA2,...,COLUNAn) VALUES (VALOR1, VALOR2,...,VALORn);


-- Inserir duas tuplas na tabela MEDICO

--Tabela MEDICO:
INSERT INTO MEDICO (MEDCODIGO, MEDNOME)
VALUES (1, 'Dr. Silva'), (2, 'Dr. Pereira');

--Tabela Consulta:
INSERT INTO Consulta (MEDCODIGO, PACCODIGO, CONCODIGO, DATA)
VALUES (1, 1, 1, '2023-01-01'), (2, 2, 2, '2023-02-02');

--Tabela PACIENTE:
INSERT INTO PACIENTE (PACCODIGO, PACCNOME)
VALUES (1, 'Paciente A'), (2, 'Paciente B');

--Tabela PRESCRICAO:
INSERT INTO PRESCRICAO (CONCODIGO, MDCODIGO, POSOLOGIA)
VALUES (1, 1, 'Tomar uma vez ao dia'), (2, 2, 'Tomar duas vezes ao dia');

--Tabela MEDICAMENTO:
INSERT INTO MEDICAMENTO (MDCODIGO, MDNOME)
VALUES (1, 'Medicamento X'), (2, 'Medicamento Y');

--5.	Fazer uma alteração em qualquer tabela, na resposta identificar o que foi alterado: (0,5). Usar o UPDATE:

UPDATE MEDICO
SET MEDNOME = 'Novo Nome'
WHERE MEDCODIGO = 1;

SELECT * FROM MEDICO WHERE MEDCODIGO = 1;

--6.	Com comando SELECT, realizar: (0,5)
--6.1	Retornar duas colunas de qualquer tabela:


SELECT MEDCODIGO, MEDNOME FROM MEDICO;

--1.1	Mostrar o nome e a data de nascimento dos médicos:

SELECT MEDNOME, MEDNASCIMENTO FROM MEDICO;


